# _config.yml
title: Asher Pope & Intrinsic Labs LLC
description: Documenting the start of thousands of projects
baseurl: "" # Change this if your site is not at root
url: "https://rocketbro.github.io"
github_username: rocketbro
permalink: pretty

# Build settings
markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

collections:
  projects:
    output: true
    permalink: /projects/:path/

sass:
  sass_dir: assets/css/_sass
  style: compressed

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  
tag_names:
  cooking-with-claude: "Cooking With Claude"
  web: "Web"
  ios: "iOS"
  android: "Android"
  dev: "Dev"
  film: "Film"
  cli: "CLI"